apiVersion: v1
kind: Namespace
metadata:
  name: cancer-core
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: cancer-ml
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: cancer-infra
